# Generated by Django 3.1 on 2020-08-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem_amounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amounts',
            new_name='amount',
        ),
    ]
