# Generated by Django 3.1 on 2020-08-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20200813_0016'),
        ('order', '0003_auto_20200812_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=200)),
                ('shipping_fee', models.IntegerField(default=60)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('0', '已成立'), ('1', '已付款'), ('2', '已出貨'), ('3', '已完成'), ('4', '已申請退回'), ('5', '已收到退回商品'), ('6', '已退款')], max_length=20)),
                ('payment', models.CharField(choices=[('0', 'ATM匯款')], max_length=20)),
                ('is_canceled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('unit_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
