# Generated by Django 3.1 on 2020-08-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200813_0016'),
        ('order', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '已初始'), ('1', '已成立'), ('2', '已付款'), ('3', '已出貨'), ('4', '已完成'), ('5', '已申請退回'), ('6', '已收到退回商品'), ('7', '已退款')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
