# Generated by Django 3.1 on 2020-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200813_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(default='41168', max_length=6),
            preserve_default=False,
        ),
    ]
