# Generated by Django 3.1 on 2020-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_shipping_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'ATM匯款')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已初始'), (1, '已成立'), (2, '已付款'), (3, '已出貨'), (4, '已完成'), (5, '已申請退回'), (6, '已收到退回商品'), (7, '已退款')], default=0),
        ),
    ]
