# Generated by Django 3.1 on 2020-08-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remittance_account',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已初始'), (1, '已成立'), (2, '已確認收到付款'), (3, '已出貨'), (4, '已完成'), (5, '已申請退回'), (6, '已收到退回商品'), (7, '已退款')], default=0),
        ),
    ]
