# Generated by Django 3.1 on 2020-08-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20200815_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_contact_phone_no',
            field=models.CharField(default='0900100200', max_length=20, verbose_name='聯絡電話'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='已取消'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'ATM匯款')], default=0, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remittance_account',
            field=models.CharField(blank=True, max_length=5, verbose_name='匯款帳號後五碼'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=200, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(default=60, verbose_name='運費'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(max_length=6, verbose_name='郵遞區號'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '已初始'), (1, '已成立'), (2, '已確認收到付款'), (3, '已出貨'), (4, '已完成'), (5, '已申請退回'), (6, '已收到退回商品'), (7, '已退款')], default=0, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='成立時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_gender',
            field=models.IntegerField(choices=[(0, '先生'), (1, '女士')], default=0, verbose_name='稱謂'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='收件人'),
        ),
    ]
