# Generated by Django 3.1 on 2020-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200815_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remittance_account',
            field=models.CharField(blank=True, max_length=5, verbose_name='匯款帳號末五碼'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(max_length=5, verbose_name='郵遞區號'),
        ),
    ]
