# Generated by Django 3.1 on 2020-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200821_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='優惠代碼')),
                ('discount_type', models.IntegerField(choices=[(0, '總金額折價'), (1, '總金額打折'), (2, '免運費')], default=0, verbose_name='優惠類型')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='折價金額')),
                ('discount_ratio', models.DecimalField(decimal_places=2, default=0.9, max_digits=3, verbose_name='打折（比例）')),
                ('total_amount_limit_type', models.IntegerField(choices=[(0, '不限制'), (1, '滿額可用')], default=0, verbose_name='滿額限制類型')),
                ('total_amount_limit', models.IntegerField(default=0, verbose_name='總金額限制')),
                ('time_limit_type', models.IntegerField(choices=[(0, '不限制'), (1, '有效期限內可用')], default=0, verbose_name='時間限制類型')),
                ('time_limit_start', models.DateTimeField(default=1598428329.789438, verbose_name='開始有效時間')),
                ('time_limit_expire', models.DateTimeField(default=1598428329.7894552, verbose_name='截止有效時間')),
            ],
        ),
    ]
