# Generated by Django 3.1 on 2020-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount_amount_limit',
            field=models.IntegerField(default=1000, verbose_name='折價上限'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='time_limit_expire',
            field=models.DateTimeField(default=1598429200.170123, verbose_name='截止有效時間'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='time_limit_start',
            field=models.DateTimeField(default=1598429200.170107, verbose_name='開始有效時間'),
        ),
    ]
