# Generated by Django 3.1 on 2020-08-26 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200826_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='discount_amount_limit',
            new_name='discount_limit',
        ),
        migrations.AddField(
            model_name='promo',
            name='discount_limit_type',
            field=models.IntegerField(choices=[(0, '不限制'), (1, '限制')], default=0, verbose_name='折價上限類型'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='time_limit_expire',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='截止有效時間'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='time_limit_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='開始有效時間'),
        ),
    ]
