# Generated by Django 3.1 on 2020-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200828_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='has_total_count_limit',
            field=models.IntegerField(choices=[(0, '無'), (1, '有')], default=0, verbose_name='數量限制'),
        ),
        migrations.AddField(
            model_name='promo',
            name='total_count_limit',
            field=models.IntegerField(default=10, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_limit',
            field=models.IntegerField(default=100, verbose_name='折價上限'),
        ),
    ]
