# Generated by Django 3.1 on 2020-08-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200828_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='優惠'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.promo', verbose_name='優惠碼'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_limit',
            field=models.IntegerField(default=100, verbose_name='最高折價上限'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='has_total_amount_limit',
            field=models.IntegerField(choices=[(0, '無'), (1, '有')], default=0, verbose_name='消費滿額才可用限制'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='total_count_limit',
            field=models.IntegerField(default=10, verbose_name='剩餘數量'),
        ),
    ]
