# Generated by Django 3.1 on 2020-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='使用次數'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='has_total_count_limit',
            field=models.IntegerField(choices=[(0, '無'), (1, '有')], default=0, verbose_name='使用次數限制'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='total_count_limit',
            field=models.IntegerField(default=10, verbose_name='最多使用次數'),
        ),
    ]
