# Generated by Django 3.1 on 2020-08-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200813_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_unit_sellable',
            new_name='is_sellable',
        ),
    ]
