# Generated by Django 3.1 on 2020-09-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='類別名稱'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='產品'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='封面照片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='概覽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.CharField(max_length=200, verbose_name='成分'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_quantity',
            field=models.IntegerField(default=0, verbose_name='庫存'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='上架'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='utility',
            field=models.CharField(max_length=200, verbose_name='用途'),
        ),
    ]
