# Generated by Django 3.1 on 2020-08-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200813_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_postal_code',
            field=models.CharField(default='41168', max_length=6),
            preserve_default=False,
        ),
    ]
