# Generated by Django 3.1 on 2020-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_userprofile_shipping_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, '先生'), (1, '女士')], default=0),
        ),
    ]
