# Generated by Django 3.1 on 2020-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_phone_no',
            field=models.CharField(default='0900100200', max_length=20),
            preserve_default=False,
        ),
    ]
