# Generated by Django 3.1 on 2020-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_userprofile_contact_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='contact_address',
            new_name='manager_address',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='contact_phone_no',
            new_name='manager_contact_phone_no',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='contact_email',
            new_name='manager_email',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='contact_manager',
            new_name='manager_name',
        ),
        migrations.AddField(
            model_name='settings',
            name='manager_bank_code',
            field=models.CharField(default='700', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='manager_bank_name',
            field=models.CharField(default='中華郵政', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='manager_receiving_account',
            field=models.CharField(default='01234569876543', max_length=30),
            preserve_default=False,
        ),
    ]
