# Generated by Django 3.1 on 2020-08-24 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0008_settings_manager_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Configuration',
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
