# Generated by Django 3.1 on 2020-08-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0010_configuration_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='discount_shipping_fee',
            field=models.IntegerField(default=2000, verbose_name='滿此金額免運費'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='manager_receiving_account_name',
            field=models.CharField(default='hi', max_length=30, verbose_name='收款帳戶名稱'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='copyright_info',
            field=models.CharField(max_length=200, verbose_name='權利聲明'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='允許顧客成立訂單'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='is_visitable',
            field=models.BooleanField(default=True, verbose_name='允許造訪網站'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_address',
            field=models.CharField(max_length=200, verbose_name='管理員地址'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_bank_code',
            field=models.CharField(max_length=5, verbose_name='收款銀行代碼'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_bank_name',
            field=models.CharField(max_length=20, verbose_name='收款銀行名稱'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_contact_phone_no',
            field=models.CharField(max_length=20, verbose_name='管理員聯絡電話'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_email',
            field=models.CharField(max_length=100, verbose_name='管理員電子郵件信箱'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='管理員姓名'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_receiving_account',
            field=models.CharField(max_length=30, verbose_name='收款帳號'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='manager_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理員'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='shipping_fee',
            field=models.IntegerField(default=60, verbose_name='每筆訂單運費'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_logo_large',
            field=models.ImageField(upload_to='administration', verbose_name='網站Logo（大）'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_logo_small',
            field=models.ImageField(upload_to='administration', verbose_name='網站Logo（小）'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='site_name',
            field=models.CharField(max_length=200, verbose_name='網站名稱'),
        ),
    ]
